### ISSUE TITLE
Helm deployment instructions are incorrect

### ISSUE THREAD

**Issue by ne0777** [kubic-project/caasp-services#46]
Portus is NOT located on the incubator repository at this time.  And yet the instructions on the 
deploy instructions reference it more than once.

https://github.com/kubic-project/caasp-services/tree/master/contrib/helm-charts/portus

https://kubernetes-charts-incubator.storage.googleapis.com/

**Comment by stefsuse** [comment]
So it isn't. This is left over from a PR from a long time ago that never got merged into incubator iirc. We'll remove the mention in a future change, thanks.

**Comment by ne0777** [comment]
Thanks,  I saw the PR and read through all of it... seems like just some last hurdles (tests) to pass to get it bumped into stable (per: https://github.com/kubernetes/charts/pull/2766).

Don't know how stale that is?  Is it still worth fighting the good fight on?

**Comment by ne0777** [comment]
Thanks,  I saw the PR and read through all of it... seems like just some last hurdles (tests) to pass to get it bumped into stable (per: https://github.com/kubernetes/charts/pull/2766).

Don't know how stale that is?  Is it still worth fighting the good fight on?

**Comment by stefsuse** [comment]
Yes that is the one. I was not involved with the project at the time so I can't speak to why it was not merged initially... but I do have to admit, that PR been open for quite a while! It looks like the most recent issue is just from requirements.lock?

With that said the 2 charts have diverged quite a bit, and the incubator PR chart is still based on openSUSE/portus:2.2 though 2.3 has had some significant updates.
