### ISSUE TITLE
installing portus with helm does not working

### ISSUE THREAD

**Issue by MBcom** [kubic-project/caasp-services#50]
when i am running `helm install --name portus-registry -f portus-config.yml  --namespace portus-registry  incubator/portus` I get the following error: `Error: failed to download "incubator/portus" (hint: running `helm repo update` may help)`  

I did already run `helm repo update` but I still getting the same error
  
Does I have to add a specific helm repo which including this helm chart for portus?

**Comment by stefsuse** [comment]
Hi MBcom. When filing bugs please include information such as helm and tiller versions and any error output you are seeing (pastebin for yuge diffs please). 

With that said this sounds like it is directly related to Helm and all related repositories moving out of the Kubernetes org. Here is the latest message from cncf-helm@lists.cncf.io: 

>The charts repo has now been moved to github.com/helm/charts. If there are any issues please let us know.
>
>Note, we may run into places where /ok-to-test needs to be re-added to a PR. This will need to be >done by those who are members of the Helm org or are collaborators on the charts repo.
>Again, if there are any questions, please let us know.

**Comment by ArcticSnowman** [comment]
@MBcom  - your command wont work as there is no incubator/portus.  To use this one you need to git clone this repo and install from there.

**Comment by MBcom** [comment]
@stefsuse @ArcticSnowman thank you - for your help - its now working for me
the wrong chart repo was the issue

/close
