### ISSUE TITLE
How to create cert and key for all the internal hostnames

### ISSUE THREAD

**Issue by mailzyok** [kubic-project/caasp-services#52]
Hi,

We want to use TLS for internal communication.

According the to comments in values.yaml, as below:
##

User need to create key/cert covering internal hostnames of poruts, registry and nginx,
Could you please provide a guide on how to create such kinds of key and cert.  For example, the internal hostnames are:
test-portus-nginx
test-portus-portus
test-portus-registry

is it one pair of key and cert which covers all the hostname, then how to create a cert which covers mulitpile hostnames?

If three pair of keys and certs are needed, how to fill the key and cert values in values.yaml?

Thanks,
yzha

**Comment by starzha** [comment]
Problem solved. Please refer to https://github.com/kubic-project/caasp-services/tree/master/docs/portus/secure/README.md

**Comment by mailzyok** [comment]
Problem solved. Please refer to https://github.com/kubic-project/caasp-services/tree/master/docs/portus/secure/README.md

yzha
